import type { SvgCompositionSpec } from "./svg-assets";

export const DEFAULT_SPEC: SvgCompositionSpec = {
  version: 1,
  asset_id: "lpc-style-character",
  view_box: [0, 0, 64, 64],
  output: { width: 256, height: 256 },
  palette: {
    cloth: "#3d5a80",
    "cloth-light": "#5a7aad",
    "cloth-shadow": "#2a3f5c",
    hair: "#6b3e26",
    "hair-light": "#8a5433",
    "hair-shadow": "#4a2a18",
    leather: "#7a4b2a",
    metal: "#c7d0d9",
    "metal-light": "#eef4f8",
    "metal-shadow": "#8a97a5",
    shadow: "#1a1c22",
    shoe: "#2b2d42",
    skin: "#f2c18d",
    "skin-light": "#ffd9ad",
    "skin-shadow": "#c98f5f",
  },
  parts: [
    {
      id: "shadow",
      part_id: "shadow-ground",
      position: [32, 58],
      anchor: "root",
      attach_to: null,
      offset: [0, 0],
      scale: 1,
      rotate: 0,
      z_index: null,
    },
    {
      id: "body",
      part_id: "body-base",
      position: [32, 56],
      anchor: "root",
      attach_to: null,
      offset: [0, 0],
      scale: 1,
      rotate: 0,
      z_index: 10,
    },
    {
      id: "shirt",
      part_id: "shirt-tunic",
      position: [0, 0],
      anchor: "root",
      attach_to: { placement_id: "body", anchor: "torso" },
      offset: [0, 0],
      scale: 1,
      rotate: 0,
      z_index: 20,
    },
    {
      id: "hair",
      part_id: "hair-short",
      position: [0, 0],
      anchor: "root",
      attach_to: { placement_id: "body", anchor: "head" },
      offset: [0, 0],
      scale: 1,
      rotate: 0,
      z_index: 30,
    },
    {
      id: "sword",
      part_id: "sword-basic",
      position: [0, 0],
      anchor: "root",
      attach_to: { placement_id: "body", anchor: "hand" },
      offset: [0, 0],
      scale: 1,
      rotate: 0,
      z_index: 40,
    },
  ],
};
