import type { SvgCompositionSpec } from "./svg-assets";

export const DEFAULT_SPEC: SvgCompositionSpec = {
  version: 1,
  asset_id: "lpc-style-character",
  view_box: [0, 0, 64, 64],
  output: { width: 256, height: 256 },
  palette: {
    cloth: "#3d5a80",
    hair: "#6b3e26",
    leather: "#7a4b2a",
    metal: "#c7d0d9",
    shoe: "#2b2d42",
    skin: "#f2c18d",
  },
  parts: [
    {
      id: "body",
      part_id: "body-base",
      position: [32, 56],
      anchor: "root",
      attach_to: null,
      offset: [0, 0],
      scale: 1,
      rotate: 0,
      z_index: 10,
    },
    {
      id: "shirt",
      part_id: "shirt-tunic",
      position: [0, 0],
      anchor: "root",
      attach_to: { placement_id: "body", anchor: "torso" },
      offset: [0, 0],
      scale: 1,
      rotate: 0,
      z_index: 20,
    },
    {
      id: "hair",
      part_id: "hair-short",
      position: [0, 0],
      anchor: "root",
      attach_to: { placement_id: "body", anchor: "head" },
      offset: [0, 0],
      scale: 1,
      rotate: 0,
      z_index: 30,
    },
    {
      id: "sword",
      part_id: "sword-basic",
      position: [0, 0],
      anchor: "root",
      attach_to: { placement_id: "body", anchor: "hand" },
      offset: [0, 0],
      scale: 1,
      rotate: 0,
      z_index: 40,
    },
  ],
};
